const cartActionTypes = {
    ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
    REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
    ENCREASE_CART_ITEM: "ENCREASE_CART_ITEM",
    DESCREASE_CART_ITEM: "DESCREASE_CART_ITEM"
};

export default cartActionTypes;
